// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OP_WebApi.Models;

namespace OP_WebApi.Migrations
{
    [DbContext(typeof(TableContext))]
    [Migration("20210909090619_op14000618A5")]
    partial class op14000618A5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OP_WebApi.Models.Action", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<long>("Cost_per_Hour");

                    b.Property<bool>("Enable");

                    b.Property<string>("Name");

                    b.Property<double>("Time");

                    b.Property<double>("Workers");

                    b.HasKey("Id");

                    b.ToTable("Action");
                });

            modelBuilder.Entity("OP_WebApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<bool>("Need_Manager_Confirmation");

                    b.Property<bool>("Need_Supervisor_Confirmation");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("OP_WebApi.Models.Collection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<long>("CurrentLevel_Index");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<bool>("IsCompleted");

                    b.Property<long>("PreviousLevel_Index");

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("OP_WebApi.Models.Collection_Action", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Action_Id");

                    b.Property<string>("Action_Name");

                    b.Property<string>("Action_Prerequisites");

                    b.Property<double>("Action_Time");

                    b.Property<long>("Action_TotalCost");

                    b.Property<double>("Action_Workers");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Collection_Id");

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Confirm_Contractor");

                    b.Property<bool>("Confirm_LineManager");

                    b.Property<bool>("Confirm_QC");

                    b.Property<long>("CurrentContractor_Id");

                    b.Property<int>("OPC_Action_Priority");

                    b.Property<int>("ProgressPercent_Planning");

                    b.Property<int>("ProgressPercent_Real");

                    b.HasKey("Id");

                    b.ToTable("Collection_Action");
                });

            modelBuilder.Entity("OP_WebApi.Models.Collection_Action_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Action_Id");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Collection_Id");

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Confirm_Contractor");

                    b.Property<bool>("Confirm_LineManager");

                    b.Property<bool>("Confirm_QC");

                    b.Property<long>("CurrentContractor_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<int>("ProgressPercent_Real");

                    b.HasKey("Id");

                    b.ToTable("Collection_Action_History");
                });

            modelBuilder.Entity("OP_WebApi.Models.Collection_Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Collection_Id");

                    b.Property<long>("Company_Id");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Item_SmallCode");

                    b.Property<string>("Item_SmallName");

                    b.Property<double>("Quantity");

                    b.HasKey("Id");

                    b.ToTable("Collection_Item");
                });

            modelBuilder.Entity("OP_WebApi.Models.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Domain");

                    b.Property<string>("EMail");

                    b.Property<DateTime>("End_DateTime_mi");

                    b.Property<string>("End_DateTime_sh");

                    b.Property<string>("Mobile");

                    b.Property<string>("OwnerName");

                    b.Property<string>("Phone");

                    b.Property<string>("Real_Name");

                    b.Property<bool>("Warehouse_AutomaticBooking");

                    b.Property<long>("Warehouse_Booking_MaxHours");

                    b.HasKey("Id");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("OP_WebApi.Models.CostCenter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<long>("Index_in_Company");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("CostCenter");
                });

            modelBuilder.Entity("OP_WebApi.Models.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<string>("Index");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<long>("User_Id");

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("OP_WebApi.Models.File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<byte[]>("Content");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<bool>("Enable");

                    b.Property<string>("OriginalFileName");

                    b.HasKey("Id");

                    b.ToTable("File");
                });

            modelBuilder.Entity("OP_WebApi.Models.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Bookable");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<double>("C_D1");

                    b.Property<double>("C_D2");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Category_Id");

                    b.Property<string>("Code_Full");

                    b.Property<string>("Code_Small");

                    b.Property<long>("Company_Id");

                    b.Property<int>("Depo_type");

                    b.Property<bool>("Enable");

                    b.Property<long>("FixedPrice");

                    b.Property<bool>("Module");

                    b.Property<string>("Name_Full");

                    b.Property<string>("Name_Samll");

                    b.Property<bool>("Need_Manager_Confirmation");

                    b.Property<bool>("Need_QC_Confirmation");

                    b.Property<double>("Quantity");

                    b.Property<bool>("Salable");

                    b.Property<long>("SalesPrice");

                    b.Property<int>("Significance_Factor");

                    b.Property<int>("Type");

                    b.Property<string>("Unit");

                    b.Property<long>("Warehouse_Id");

                    b.Property<double>("Weight");

                    b.Property<double>("Wh_OrderPoint");

                    b.Property<double>("Wh_OrderQuantity");

                    b.Property<double>("Wh_Quantity_Booking");

                    b.Property<double>("Wh_Quantity_Real");

                    b.Property<double>("Wh_Quantity_x");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("OP_WebApi.Models.Item_File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Enable");

                    b.Property<long>("File_Index");

                    b.Property<string>("Item_Code_Small");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Item_File");
                });

            modelBuilder.Entity("OP_WebApi.Models.Item_OPC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Item_SmallCode");

                    b.Property<long>("OPC_Id");

                    b.HasKey("Id");

                    b.ToTable("Item_OPC");
                });

            modelBuilder.Entity("OP_WebApi.Models.Item_Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ChangingValue");

                    b.Property<long>("Company_Id");

                    b.Property<string>("DefaultValue");

                    b.Property<string>("Item_Code_Small");

                    b.Property<long>("Item_Id");

                    b.Property<long>("Property_Index");

                    b.HasKey("Id");

                    b.ToTable("Item_Property");
                });

            modelBuilder.Entity("OP_WebApi.Models.LoginHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("Date_sh");

                    b.Property<string>("Time");

                    b.Property<long>("User_Id");

                    b.Property<string>("User_RealName");

                    b.HasKey("Id");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("OP_WebApi.Models.Module", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Enable");

                    b.Property<string>("Item_Code_Small");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Module_Code_Small");

                    b.Property<double>("Quantity");

                    b.Property<string>("Unit");

                    b.HasKey("Id");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("OP_WebApi.Models.OL_Prerequisite", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<long>("OL_Id");

                    b.Property<long>("Prerequisite_Id");

                    b.HasKey("Id");

                    b.ToTable("OL_Prerequisite");
                });

            modelBuilder.Entity("OP_WebApi.Models.OL_UL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<long>("OL_Id");

                    b.Property<long>("UL_Id");

                    b.HasKey("Id");

                    b.ToTable("OL_UL");
                });

            modelBuilder.Entity("OP_WebApi.Models.OPC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Enable");

                    b.Property<string>("Name");

                    b.Property<double>("Time");

                    b.HasKey("Id");

                    b.ToTable("OPC");
                });

            modelBuilder.Entity("OP_WebApi.Models.OPC_Acions", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Action_Id");

                    b.Property<string>("Action_Prerequisites");

                    b.Property<long>("Company_Id");

                    b.Property<long>("OPC_Id");

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("OPC_Acion");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<long>("CurrentLevel_Id");

                    b.Property<string>("Customer_Index");

                    b.Property<string>("Customer_Name");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("Date_sh");

                    b.Property<string>("Index");

                    b.Property<long>("Index_in_Company");

                    b.Property<string>("Level_Description");

                    b.Property<long>("NextLevel_Id");

                    b.Property<string>("Order_Description");

                    b.Property<long>("PreviousLevel_Id");

                    b.Property<string>("Time");

                    b.Property<string>("Title");

                    b.Property<long>("User_Id");

                    b.Property<int>("type");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("OP_WebApi.Models.OrderPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<double>("CanTakeQuantity");

                    b.Property<long>("Company_Id");

                    b.Property<bool>("IsCompleted");

                    b.Property<string>("Order_Index");

                    b.Property<string>("Order_Title");

                    b.Property<int>("Priority");

                    b.Property<int>("ProgressPercent");

                    b.Property<double>("RemainedQuantity");

                    b.Property<double>("TotalQuantity");

                    b.HasKey("Id");

                    b.ToTable("OrderPriority");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Enable");

                    b.Property<long>("File_Index");

                    b.Property<string>("Order_Index");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Order_Attachment");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<string>("Customer_Index");

                    b.Property<string>("Order_Index");

                    b.HasKey("Id");

                    b.ToTable("Order_Customer");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<string>("OrderLevel_Description");

                    b.Property<long>("OrderLevel_Id");

                    b.Property<string>("Order_Index");

                    b.Property<long>("User_Id");

                    b.Property<long>("User_Level_Id");

                    b.Property<string>("User_Name");

                    b.HasKey("Id");

                    b.ToTable("Order_History");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<long>("FixedPrice");

                    b.Property<long>("Item_Id");

                    b.Property<bool>("Item_Module");

                    b.Property<string>("Item_Name_Samll");

                    b.Property<string>("Item_SmallCode");

                    b.Property<string>("Module_SmallCode");

                    b.Property<string>("Order_Index");

                    b.Property<double>("Quantity");

                    b.Property<long>("SalesPrice");

                    b.HasKey("Id");

                    b.ToTable("Order_Item");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_Item_Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<int>("ItemBatch_Counter");

                    b.Property<int>("ItemOrder_Counter");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Item_SmallCode");

                    b.Property<long>("OI_Index");

                    b.Property<string>("Order_Index");

                    b.Property<bool>("Property_ChangingValue");

                    b.Property<string>("Property_Description");

                    b.Property<long>("Property_Index");

                    b.Property<string>("Property_Name");

                    b.Property<string>("Property_Value");

                    b.HasKey("Id");

                    b.ToTable("Order_Item_Property");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("CancelingLevel");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<string>("Description2");

                    b.Property<bool>("Enabled");

                    b.Property<bool>("FirstLevel");

                    b.Property<bool>("LastLevel");

                    b.Property<string>("MessageText");

                    b.Property<bool>("OrderCanChange");

                    b.Property<bool>("RemovingLevel");

                    b.Property<bool>("ReturningLevel");

                    b.Property<long>("Sequence");

                    b.Property<int>("Type");

                    b.Property<string>("Type_Description");

                    b.HasKey("Id");

                    b.ToTable("Order_Level");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_Level_on_Returning", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<long>("OL_Retruned_Id");

                    b.Property<long>("OrderLevel_Id");

                    b.HasKey("Id");

                    b.ToTable("Order_Level_on_Returning");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_OL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<long>("OrderLevel_Id");

                    b.Property<string>("Order_Index");

                    b.HasKey("Id");

                    b.ToTable("Order_OL");
                });

            modelBuilder.Entity("OP_WebApi.Models.Order_StockItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<string>("Comment");

                    b.Property<long>("Company_Id");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Item_Name_Samll");

                    b.Property<string>("Item_SmallCode");

                    b.Property<string>("Order_Index");

                    b.Property<double>("Quantity");

                    b.Property<double>("Quantity_CanTake");

                    b.Property<double>("Quantity_Remained");

                    b.Property<string>("Top_Code");

                    b.Property<string>("Top_Name");

                    b.Property<long>("WarehouseIndex");

                    b.HasKey("Id");

                    b.ToTable("Order_StockItem");
                });

            modelBuilder.Entity("OP_WebApi.Models.OrdersCollection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Collection_Id");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Order_Index");

                    b.HasKey("Id");

                    b.ToTable("OrdersCollection");
                });

            modelBuilder.Entity("OP_WebApi.Models.Proforma", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Confirmor10Sign_Index");

                    b.Property<string>("Confirmor20Sign_Index");

                    b.Property<string>("Confirmor30Sign_Index");

                    b.Property<string>("Confirmor90Sign_Index");

                    b.Property<string>("Customer_Index");

                    b.Property<string>("Customer_Name");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<double>("Discount1");

                    b.Property<double>("Discount2");

                    b.Property<double>("Discount3");

                    b.Property<double>("Discount4");

                    b.Property<double>("DiscountPayment_Factor");

                    b.Property<bool>("Enable");

                    b.Property<string>("Index");

                    b.Property<long>("Order_Id");

                    b.Property<string>("Order_Index");

                    b.Property<string>("Order_ProformaNo");

                    b.Property<string>("PaymentMethod_Description");

                    b.Property<string>("RegSign_Index");

                    b.Property<double?>("Tax");

                    b.Property<int>("TotalPrice_NetPayable");

                    b.Property<int>("TotalPrice_withoutDiscount");

                    b.Property<long>("User_Id");

                    b.HasKey("Id");

                    b.ToTable("Proforma");
                });

            modelBuilder.Entity("OP_WebApi.Models.Proforma_Row", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<int?>("Depo_type");

                    b.Property<double>("Discount_Quantity");

                    b.Property<bool>("DontShow_in_Output");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Item_SmallCode");

                    b.Property<string>("Item_SmallName");

                    b.Property<long>("Order_Id");

                    b.Property<string>("Order_Index");

                    b.Property<int>("PriceRow_withDiscount");

                    b.Property<int>("PriceRow_withoutDiscount");

                    b.Property<long>("PriceUnit_withoutDiscount");

                    b.Property<string>("Proforma_Index");

                    b.Property<int>("Quantity");

                    b.Property<long>("User_Id");

                    b.HasKey("Id");

                    b.ToTable("Proforma_Row");
                });

            modelBuilder.Entity("OP_WebApi.Models.Property", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<bool>("ChangingValue");

                    b.Property<long>("Company_Id");

                    b.Property<string>("DefaultValue");

                    b.Property<string>("Description");

                    b.Property<bool>("Enable");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("OP_WebApi.Models.PurchaseRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("PurchaseRequest");
                });

            modelBuilder.Entity("OP_WebApi.Models.UL_Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<bool>("Enabled");

                    b.Property<string>("Unique_Phrase");

                    b.HasKey("Id");

                    b.ToTable("UL_Feature");
                });

            modelBuilder.Entity("OP_WebApi.Models.UL_Request_Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<long>("Category_Id");

                    b.Property<long>("Company_Id");

                    b.Property<long>("Supervisor_UL_Id");

                    b.Property<long>("User_Level_Id");

                    b.HasKey("Id");

                    b.ToTable("UL_Request_Category");
                });

            modelBuilder.Entity("OP_WebApi.Models.UL_See_OL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<long>("OL_Id");

                    b.Property<long>("UL_Id");

                    b.HasKey("Id");

                    b.ToTable("UL_See_OL");
                });

            modelBuilder.Entity("OP_WebApi.Models.UL_See_UL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<long>("Company_Id");

                    b.Property<long>("MainUL_Id");

                    b.Property<long>("UL_Id");

                    b.HasKey("Id");

                    b.ToTable("UL_See_UL");
                });

            modelBuilder.Entity("OP_WebApi.Models.Unit", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Enable");

                    b.Property<string>("Name");

                    b.Property<double>("Time");

                    b.HasKey("Id");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("OP_WebApi.Models.Unit_Acion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Action_Id");

                    b.Property<long>("Company_Id");

                    b.Property<long>("Unit_Id");

                    b.HasKey("Id");

                    b.ToTable("Unit_Acion");
                });

            modelBuilder.Entity("OP_WebApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Address");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<string>("EMail");

                    b.Property<DateTime>("End_DateTime_mi");

                    b.Property<string>("End_DateTime_sh");

                    b.Property<bool>("IsDefault");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("Real_Name");

                    b.Property<string>("UserLevel_Description");

                    b.Property<long>("UserLevel_Id");

                    b.Property<string>("User_Domain");

                    b.Property<long>("User_Id_Creator");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("OP_WebApi.Models.User_File", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<bool>("Enable");

                    b.Property<string>("File_Id");

                    b.Property<int>("Type");

                    b.Property<long>("User_Id");

                    b.HasKey("Id");

                    b.ToTable("User_File");
                });

            modelBuilder.Entity("OP_WebApi.Models.User_Level", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<bool>("Enabled");

                    b.Property<int>("Type");

                    b.Property<string>("Unit_Name");

                    b.HasKey("Id");

                    b.ToTable("User_Level");
                });

            modelBuilder.Entity("OP_WebApi.Models.User_Level_UL_Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<bool>("UL_Feature_Enabled");

                    b.Property<long>("UL_Feature_Id");

                    b.Property<string>("UL_Feature_Unique_Phrase");

                    b.Property<long>("User_Level_Id");

                    b.HasKey("Id");

                    b.ToTable("User_Level_UL_Feature");
                });

            modelBuilder.Entity("OP_WebApi.Models.User_UL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<string>("UL_Description");

                    b.Property<long>("UL_Id");

                    b.Property<long>("User_Id");

                    b.HasKey("Id");

                    b.ToTable("User_UL");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Address");

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.HasKey("Id");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse_Remittance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<int>("C_I1");

                    b.Property<int>("C_I2");

                    b.Property<long>("C_L1");

                    b.Property<long>("C_L2");

                    b.Property<string>("C_S1");

                    b.Property<string>("C_S2");

                    b.Property<string>("C_S3");

                    b.Property<long>("Company_Id");

                    b.Property<long>("Contractor_Id");

                    b.Property<string>("Contractor_Name");

                    b.Property<string>("Customer_Index");

                    b.Property<string>("Customer_Name");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<long>("Index_in_Company");

                    b.Property<int>("Type");

                    b.Property<string>("User_Id");

                    b.Property<string>("User_Name");

                    b.Property<int>("Warehouse_Id");

                    b.Property<string>("cost_center_Descripiton");

                    b.Property<long>("cost_center_Index");

                    b.HasKey("Id");

                    b.ToTable("Warehouse_Remittance");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse_Remittance_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<long>("User_Id");

                    b.Property<long>("User_Level_Id");

                    b.Property<string>("User_Name");

                    b.Property<long>("Warehouse_Remittance_Id");

                    b.HasKey("Id");

                    b.ToTable("Warehouse_Remittance_History");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse_Remittance_Row", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<long>("Company_Id");

                    b.Property<string>("Description");

                    b.Property<string>("Item_Id");

                    b.Property<string>("Item_Name");

                    b.Property<string>("Item_SmallCode");

                    b.Property<string>("Item_Unit");

                    b.Property<byte>("Manager_Confirmation_Type");

                    b.Property<DateTime>("Manager_DateTime_mi");

                    b.Property<string>("Manager_DateTime_sh");

                    b.Property<bool>("Need_Manager_Confirmation");

                    b.Property<bool>("Need_QC_Confirmation");

                    b.Property<byte>("QC_Confirmation_Type");

                    b.Property<DateTime>("QC_DateTime_mi");

                    b.Property<string>("QC_DateTime_sh");

                    b.Property<double>("Quantity");

                    b.Property<double>("Quantity_Confirmed");

                    b.Property<double>("Quantity_QC_Confirmed");

                    b.Property<long>("Warehouse_Remittance_Id");

                    b.HasKey("Id");

                    b.ToTable("Warehouse_Remittance_Row");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse_Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("DateTime_sh");

                    b.Property<string>("Description");

                    b.Property<long>("Index_in_Company");

                    b.Property<bool>("Need_Supervisor_Confirmation");

                    b.Property<string>("Order_Index");

                    b.Property<bool>("Request_Canceled");

                    b.Property<bool>("Request_Completed");

                    b.Property<bool>("Request_Ready_to_Get");

                    b.Property<bool>("Sent_to_Warehouse");

                    b.Property<string>("Status_Description");

                    b.Property<string>("Unit_Name");

                    b.Property<long>("UserLevel_Id");

                    b.Property<long>("User_Id");

                    b.Property<string>("User_Name");

                    b.HasKey("Id");

                    b.ToTable("Warehouse_Request");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse_Request_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Company_Id");

                    b.Property<DateTime>("DateTime_mi");

                    b.Property<string>("Date_sh");

                    b.Property<string>("Description");

                    b.Property<string>("Time");

                    b.Property<long>("User_Id");

                    b.Property<long>("User_Level_Id");

                    b.Property<string>("User_Name");

                    b.Property<long>("Warehouse_Request_Id");

                    b.HasKey("Id");

                    b.ToTable("Warehouse_Request_History");
                });

            modelBuilder.Entity("OP_WebApi.Models.Warehouse_Request_Row", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("C_B1");

                    b.Property<bool>("C_B2");

                    b.Property<bool>("C_B3");

                    b.Property<bool>("Canceled");

                    b.Property<long>("Company_Id");

                    b.Property<long>("CostCenter_Id");

                    b.Property<long>("Item_Category_Id");

                    b.Property<long>("Item_Id");

                    b.Property<string>("Item_Name");

                    b.Property<string>("Item_SmallCode");

                    b.Property<string>("Item_Unit");

                    b.Property<bool>("Need_Supervisor_Confirmation");

                    b.Property<double>("Quantity");

                    b.Property<bool>("Ready_to_Get");

                    b.Property<string>("Reason_of_Cancelling");

                    b.Property<string>("Status_Description");

                    b.Property<long>("Supervisor_Confirmer_LevelIndex");

                    b.Property<long>("Warehouse_Request_Id");

                    b.Property<long>("Warehouse_Request_Id_in_Company");

                    b.HasKey("Id");

                    b.ToTable("Warehouse_Request_Row");
                });
#pragma warning restore 612, 618
        }
    }
}
